default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: heroku_rails_example_development

test:
  <<: *default
  database: heroku_rails_example_test

production:
  <<: *default
  database: heroku_rails_example_production
